#include "mappings.h"

const int defaultMappingsLength = 13;
pinMap defaultMappings[defaultMappingsLength] = {
  { PSP_HOME, MISC_BUTTON_SYSTEM, TYPE_SYSTEM },
  { PSP_START, MISC_BUTTON_HOME, TYPE_SYSTEM },
  { PSP_DISPLAY, BUTTON_THUMB_R, TYPE_BUTTONS },
  
  { PSP_L1, BUTTON_SHOULDER_L, TYPE_BUTTONS  },
  { PSP_R1, BUTTON_SHOULDER_R, TYPE_BUTTONS },
  
  { PSP_DUP, DPAD_UP, TYPE_DPAD  },
  { PSP_DDOWN, DPAD_DOWN, TYPE_DPAD  },
  { PSP_DRIGHT, DPAD_RIGHT, TYPE_DPAD  },
  { PSP_DLEFT, DPAD_LEFT, TYPE_DPAD  },
  
  { PSP_CROSS, BUTTON_A, TYPE_BUTTONS  },
  { PSP_CIRCLE, BUTTON_B, TYPE_BUTTONS  },
  { PSP_SQUARE, BUTTON_X, TYPE_BUTTONS  },
  { PSP_TRIANGLE, BUTTON_Y, TYPE_BUTTONS  },
};

const int FPSMappingsLength = 18;
pinMap FPSMappings[FPSMappingsLength] = {
  { PSP_HOME, MISC_BUTTON_SYSTEM, TYPE_SYSTEM },
  { PSP_START, MISC_BUTTON_HOME, TYPE_SYSTEM },
  { PSP_DISPLAY, BUTTON_THUMB_R, TYPE_BUTTONS },

  { PSP_L1, BUTTON_SHOULDER_L, TYPE_BUTTONS  },
  { PSP_R1, BUTTON_SHOULDER_R, TYPE_BUTTONS },
  { PSP_R1, BUTTON_THROTTLE, TYPE_TRIGGER },
  
  { PSP_DDOWN, BUTTON_A, TYPE_BUTTONS  },
  { PSP_DRIGHT, BUTTON_B, TYPE_BUTTONS  },
  { PSP_DLEFT, BUTTON_X, TYPE_BUTTONS  },
  { PSP_DUP, BUTTON_Y, TYPE_BUTTONS  },
  
  { PSP_LS_UP, RS_UP, TYPE_RS },
  { PSP_LS_LEFT, RS_LEFT, TYPE_RS },
  { PSP_LS_RIGHT, RS_RIGHT, TYPE_RS },
  { PSP_LS_DOWN, RS_DOWN, TYPE_RS },

  { PSP_TRIANGLE, DPAD_UP, TYPE_DPAD  },
  { PSP_CROSS, DPAD_DOWN, TYPE_DPAD  },
  { PSP_CIRCLE, DPAD_RIGHT, TYPE_DPAD  },
  { PSP_SQUARE, DPAD_LEFT, TYPE_DPAD  },
};
