#include "mappings.h"

uint8_t defaultMappingsLength = 14;
pinMap defaultMappings[14] = {
  { PSP_HOME, CTR_MISC_BUTTON_SYSTEM, CTR_TYPE_SYSTEM },
  { PSP_START, CTR_MISC_BUTTON_HOME, CTR_TYPE_SYSTEM },
  //{ PSP_DISPLAY, CTR_BUTTON_THUMB_R, CTR_TYPE_BUTTONS },
  { PSP_SELECT, CTR_MISC_BUTTON_BACK, CTR_TYPE_SYSTEM },
  
  { PSP_L1, CTR_BUTTON_SHOULDER_L, CTR_TYPE_BUTTONS  },
  { PSP_R1, CTR_BUTTON_SHOULDER_R, CTR_TYPE_BUTTONS },
  
  { PSP_DUP, CTR_DPAD_UP, CTR_TYPE_DPAD  },
  { PSP_DDOWN, CTR_DPAD_DOWN, CTR_TYPE_DPAD  },
  { PSP_DRIGHT, CTR_DPAD_RIGHT, CTR_TYPE_DPAD  },
  { PSP_DLEFT, CTR_DPAD_LEFT, CTR_TYPE_DPAD  },
  
  { PSP_CROSS, CTR_BUTTON_A, CTR_TYPE_BUTTONS  },
  { PSP_CIRCLE, CTR_BUTTON_B, CTR_TYPE_BUTTONS  },
  { PSP_SQUARE, CTR_BUTTON_X, CTR_TYPE_BUTTONS  },
  { PSP_TRIANGLE, CTR_BUTTON_Y, CTR_TYPE_BUTTONS  },
  
  { PSP_LS, CTR_BUTTON_TS, CTR_TYPE_LS },
};

uint8_t FPSMappingsLength = 19;
pinMap FPSMappings[19] = {
  { PSP_HOME, CTR_MISC_BUTTON_SYSTEM, CTR_TYPE_SYSTEM },
  { PSP_START, CTR_MISC_BUTTON_HOME, CTR_TYPE_SYSTEM },
  { PSP_SELECT, CTR_MISC_BUTTON_BACK, CTR_TYPE_SYSTEM },

  { PSP_L1, CTR_BUTTON_SHOULDER_L, CTR_TYPE_BUTTONS  },
  { PSP_R1, CTR_BUTTON_SHOULDER_R, CTR_TYPE_BUTTONS },
  { PSP_R1, CTR_BUTTON_THROTTLE, CTR_TYPE_TRIGGER },
  
  { PSP_DDOWN, CTR_BUTTON_A, CTR_TYPE_BUTTONS  },
  { PSP_DRIGHT, CTR_BUTTON_B, CTR_TYPE_BUTTONS  },
  { PSP_DLEFT, CTR_BUTTON_X, CTR_TYPE_BUTTONS  },
  { PSP_DUP, CTR_BUTTON_Y, CTR_TYPE_BUTTONS  },
  
  { PSP_TRIANGLE, CTR_BUTTON_UP, CTR_TYPE_RS },
  { PSP_SQUARE, CTR_BUTTON_LEFT, CTR_TYPE_RS },
  { PSP_CIRCLE, CTR_BUTTON_RIGHT, CTR_TYPE_RS },
  { PSP_CROSS, CTR_BUTTON_DOWN, CTR_TYPE_RS },
  
  { PSP_LS, CTR_BUTTON_TS, CTR_TYPE_LS },

  { PSP_TRIANGLE, CTR_DPAD_UP, CTR_TYPE_DPAD  },
  { PSP_CROSS, CTR_DPAD_DOWN, CTR_TYPE_DPAD  },
  { PSP_CIRCLE, CTR_DPAD_RIGHT, CTR_TYPE_DPAD  },
  { PSP_SQUARE, CTR_DPAD_LEFT, CTR_TYPE_DPAD  },
};

uint8_t PS1MappingsLength = 21;
pinMap PS1Mappings[21] = {
  { PSP_HOME, CTR_MISC_BUTTON_SYSTEM, CTR_TYPE_SYSTEM },
  { PSP_START, CTR_MISC_BUTTON_HOME, CTR_TYPE_SYSTEM },
  { PSP_LS_LEFT, CTR_BUTTON_THUMB_R, CTR_TYPE_BUTTONS },
  { PSP_SELECT, CTR_MISC_BUTTON_BACK, CTR_TYPE_SYSTEM },

  { PSP_L1, CTR_BUTTON_SHOULDER_L, CTR_TYPE_BUTTONS  },
  { PSP_R1, CTR_BUTTON_SHOULDER_R, CTR_TYPE_BUTTONS },
  //{ PSP_LS_RIGHT, CTR_BUTTON_BRAKE, CTR_TYPE_TRIGGER }, -- XBOX Controller its broken so commented out
  { PSP_LS_RIGHT, CTR_BUTTON_TRIGGER_L, CTR_TYPE_BUTTONS },
  { PSP_LS_LEFT, CTR_BUTTON_THROTTLE, CTR_TYPE_TRIGGER },
  { PSP_LS_LEFT, CTR_BUTTON_TRIGGER_R, CTR_TYPE_BUTTONS },
    
  { PSP_CROSS, CTR_BUTTON_A, CTR_TYPE_BUTTONS  },
  { PSP_CIRCLE, CTR_BUTTON_B, CTR_TYPE_BUTTONS  },
  { PSP_SQUARE, CTR_BUTTON_X, CTR_TYPE_BUTTONS  },
  { PSP_TRIANGLE, CTR_BUTTON_Y, CTR_TYPE_BUTTONS  },
  
  { PSP_DUP, CTR_BUTTON_UP, CTR_TYPE_LS },
  { PSP_DLEFT, CTR_BUTTON_LEFT, CTR_TYPE_LS },
  { PSP_DRIGHT, CTR_BUTTON_RIGHT, CTR_TYPE_LS },
  { PSP_DDOWN, CTR_BUTTON_DOWN, CTR_TYPE_LS },

  { PSP_DUP, CTR_DPAD_UP, CTR_TYPE_DPAD  },
  { PSP_DDOWN, CTR_DPAD_DOWN, CTR_TYPE_DPAD  },
  { PSP_DRIGHT, CTR_DPAD_RIGHT, CTR_TYPE_DPAD  },
  { PSP_DLEFT, CTR_DPAD_LEFT, CTR_TYPE_DPAD  },
};

pinMap *MAPPINGS_pins = defaultMappings;
uint8_t MAPPINGS_pin_size = defaultMappingsLength;

uint8_t mode = 0;

void MAPPINGS_next_mapping() {
  mode++;

  if (mode > 2)
    mode = 0;

  PSP_mark_all_for_release();
  PSP_release_unused();

  switch (mode) {
    case 0:
      MAPPINGS_pins = defaultMappings;
      MAPPINGS_pin_size = defaultMappingsLength;
    break;
    case 1:
      MAPPINGS_pins = FPSMappings;
      MAPPINGS_pin_size = FPSMappingsLength;
    break;
    case 2:
      MAPPINGS_pins = PS1Mappings;
      MAPPINGS_pin_size = PS1MappingsLength;
  }

  //myGamepad->setPlayerLEDs((mode + 1) & 0x0f);

  Serial.print("Changing Mode ");
  Serial.print(mode);
  Serial.println("");
}
