M48
; DRILL file {KiCad (6.0.1)} date Mon Sep 26 20:40:01 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-09-26T20:40:01+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.1)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1181
%
G90
G05
T1
X4.4Y-1.9
X4.4Y-3.7
X6.4Y-1.1
X7.8Y-1.1
X7.8Y-3.7
T2
X6.437Y-3.5728
X6.8799Y-3.5827
X7.3228Y-3.563
T0
M30
