name: build-installer
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Bluepad 32
        uses: robinraju/release-downloader@v1.5
        with:
          repository: ricardoquesada/bluepad32
          tag: release_v3.5.1
          fileName: bluepad32-nina-v3.5.1.tar.gz
          out-file-path: bluepad

      - name: Extract Bluepad
        run: tar -xvzf bluepad32-nina-v3.5.1.tar.gz
        working-directory: bluepad

      - uses: actions/checkout@v3
        name: checkout PSP-consolizer
        with:
          path: main

      - uses: actions/checkout@master
        name: Checkout installer
        with:
          repository: ste2425/psp-consolizer-installer
          path: installer

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
      - uses: arduino/setup-arduino-cli@v1

      - name: Install Arduino platform
        run: |
          arduino-cli core update-index
          arduino-cli core install arduino:samd

      - name: Compile Sketch
        run: arduino-cli compile --fqbn arduino:samd:nano_33_iot psp-consolizer -e
        working-directory: main/software

      - name: Run yarn install
        run: yarn
        working-directory: installer

      - name: Copy binaries
        run: |
          copy main\software\psp-consolizer\build\arduino.samd.nano_33_iot\psp-consolizer.ino.bin installer\PSP-Bluetooth-Controller.ino.bin
          copy bluepad\bluepad32-nina-v3.5.1\bluepad32-nina-full-v3.5.1.bin installer\bluepad32-nina.bin
          Get-Content installer\config.json -Raw | ConvertFrom-Json | ForEach-Object {  $_.commitMessage = '${{ github.event.head_commit.message }}'; $_.commitsha = '${{ github.event.head_commit.id }}'; $_.expectedFirmwareVersionText = 'Bluepad32 for NINA v3.5.1'; $_ } | ConvertTo-Json | Set-Content installer\config.json

      - name: Run yarn package
        run: yarn package
        working-directory: installer

      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Installer
          path: |
            main/hardware/psp-bluetooth/Gerber/PSP-Consolizer-v1.0.zip
            main/hardware/psp-bluetooth/psp-bluetooth_bom_jlc.csv
            main/hardware/psp-bluetooth/psp-bluetooth_cpl_jlc.csv
            installer/build/psp-consoliser-programmer 1.0.0.exe
            main/docs/build guide.pdf
            main/docs/user guide.pdf
            main/3D models/PSP and Arduino mount.stl

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          prerelease: true
          files: |
            main/hardware/psp-bluetooth/Gerber/PSP-Consolizer-v1.0.zip
            main/hardware/psp-bluetooth/psp-bluetooth_bom_jlc.csv
            main/hardware/psp-bluetooth/psp-bluetooth_cpl_jlc.csv
            installer/build/psp-consoliser-programmer 1.0.0.exe
            main/docs/build guide.pdf
            main/docs/user guide.pdf
            main/3D models/PSP and Arduino mount.stl
